#!/usr/bin/python3

import sys
import sqlite3 as sql

from function import *

db = sql.connect("base.sqlite3")
interface = db.cursor()
interface.execute(r"""CREATE TABLE IF NOT EXISTS "login" (username TEXT, password INTEGER)""");
interface.execute(r"""CREATE TABLE IF NOT EXISTS "forum" (id INTEGER PRIMARY KEY, name TEXT)""");
interface.execute(r"""CREATE TABLE IF NOT EXISTS "message" (id INTEGER PRIMARY KEY, author TEXT, timestamp INTEGER, message TEXT)""");
interface.execute(r"""CREATE TABLE IF NOT EXISTS "log" (idforum INTEGER, idmessage INTEGER)""");
interface.execute(r"""CREATE TABLE IF NOT EXISTS "answer" (idmessage INTEGER, idanswer INTEGER)""");

db.commit()

headers = "HTTP/1.1 200 OK\nContent-Type:application/json\nAccess-Control-Allow-Origin:*\n\n"

forum_list = interface.execute("""SELECT name FROM forum""")
forum_list = forum_list.fetchall()
sys.stderr.write(str(forum_list) + "\n")

username = get_cookie("LOGIN")
password = get_cookie("PWD")

args = load_post_args()
forum_name = args.get("forum_name")

cookies = ""
redirectUrl = "../../forum.html"
if username == None or password == None:
    redirectUrl = "../../login.html"

elif (username and password and not (forum_name, ) in forum_list):
    interface.execute("INSERT INTO forum (name) VALUES(?)", (forum_name,))
    db.commit()
    redirectUrl = "../../index.html"
db.close()

page = """Content-type:text/html
{cookies}
Location: {url}

<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf-8" http-equiv="refresh" content="0;url={url}">
        <title>Redirection</title>
    </head>
    <body>
        <p>Redirection ... <a href="{url}">Cliquer ici si vous n'êtes pas rediriger</a>
    </body>
</html>
""".format(cookies=cookies, url=redirectUrl)

sys.stdout.write(page)